# Header
menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/chinapandaman
  RSS: /atom.xml

# Content
excerpt_link: read more

# Favicon
favicon: /images/favicon.ico

# Settings toggle
settings: false

# Code CSS toggle
highlight: true

# Word count (needs hexo-wordcount)
word_count: false

# Google Analytics
google_analytics:
  enable: false
  acct: "UA-000000000-0"

# IntenseDebate ID
intensedebate:
  enable: false
  acct: "00000000000000000000000000000000"
